#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.2 on Sun Aug 07 15:40:16 2016
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.text_ctrl_2 = wx.TextCtrl(self, wx.ID_ANY, ("http://192.168.1.40/do_value/slot_0/ch_0"))
        self.button_1 = wx.Button(self, wx.ID_ANY, ("GET"))
        self.text_ctrl_3 = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.text_ctrl_4 = wx.TextCtrl(self, wx.ID_ANY, ("http://192.168.1.40/do_value/slot_0/ch_0"))
        self.text_ctrl_5 = wx.TextCtrl(self, wx.ID_ANY, ('{"Val":1}'), style=wx.TE_MULTILINE)
        self.button_2 = wx.Button(self, wx.ID_ANY, ("Quit"))
        self.button_3 = wx.Button(self, wx.ID_ANY, ("POST"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.GetClick, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.QuitClick, self.button_2)
        self.Bind(wx.EVT_BUTTON, self.PostClick, self.button_3)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(("RESTful"))
        self.SetSize((474, 495))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_2 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, ("RESTful")), wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.text_ctrl_1, 10, wx.EXPAND, 0)
        sizer_2.Add(self.text_ctrl_2, 0, wx.EXPAND, 0)
        sizer_2.Add(self.button_1, 0, wx.ALIGN_RIGHT, 0)
        sizer_2.Add(self.text_ctrl_3, 10, wx.EXPAND, 0)
        sizer_2.Add(self.text_ctrl_4, 0, wx.EXPAND, 0)
        sizer_2.Add(self.text_ctrl_5, 5, wx.EXPAND, 0)
        sizer_3.Add(self.button_2, 0, wx.ALIGN_RIGHT, 0)
        sizer_3.Add(self.button_3, 0, wx.ALIGN_RIGHT, 0)
        sizer_2.Add(sizer_3, 1, wx.ALIGN_RIGHT, 8)
        self.SetSizer(sizer_2)
        self.Layout()
        # end wxGlade

    def GetClick(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'GetClick' not implemented!"
        event.Skip()

    def QuitClick(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'QuitClick' not implemented!"
        event.Skip()

    def PostClick(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'PostClick' not implemented!"
        event.Skip()

# end of class MyFrame
